version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "pip"
    directory: "scripts/extract-toogoodtogo-invoices"
    schedule:
      interval: "weekly"
      day: "saturday"